name: Myles Blackwood
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55408
title: 'a dad, in houston, wanting time with his child'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0c0b'
    - '#dbdee7'
    - '#6c7678'
    - '#a19972'
    - '#91402b'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
