typography_spectrum: 0.71968
color:
  brandColors:
    - '#0a0c0b'
    - '#dbdee7'
    - '#6c7678'
    - '#a19972'
    - '#91402b'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Myles Blackwood
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: bbb
    url: 'http://blog.blackwood.bike'
    type: external
favicon: null
title: 'a dad, in houston, wanting time with his child'
purpose: []
