name: Myles Blackwood
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48495
title: 'a dad, in houston, wanting time with his child'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3b5998'
    - '#9197a3'
    - '#323232'
  brandStrength: 0.46695293951779604
  lightness: 0.6005428778007627
  saturation: 0.8005534771364182
  rhythmicContrast: 0.6608721783850342
purpose: []
