typography_spectrum: 0.3786517200060189
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.14683624124154449
  lightness: 0.5451331352815032
  saturation: 0.5583118428476155
  rhythmicContrast: 0.3680834914557636
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5238762979861349
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Myles Blackwood
  email: myles.blackwood@gmail.com
  url: 'https://www.facebook.com/myles.blackwood'
name: Myles Blackwood
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'a boy, his dad, and some life in between'
description: 'okay, I''ll start here... '
purpose:
  - type: contact
    url: 'mailto:myles.blackwood@gmail.com'
    label: Contact me
  - type: contact
    url: 'tel:7132421847'
    label: Call 7132421847
content: []
github: true
